name: bf test and build

on:
  push:
    tags:
      - 'v*'

permissions:
  packages: write
  contents: write

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Test
        uses: robherley/go-test-action@v0
      - name: build
        uses: actions/setup-go@v5
      - run: go build
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.ref}}
          release_name: bf ${{github.ref}}
      - name: release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: ./bf
          asset_name: 'bf ${{github.ref_name}}.run'
          asset_content_type: application/octet-stream
